p_cas:
  logger_startup_message: 'Logger just got started!!! (from demo app config)'
  protocol:
    login:
      uri: https://ecas.ec.europa.eu/cas/login
      allowed_parameters:
        - service
        - renew
        - gateway
    servicevalidate:
      uri: https://ecas.ec.europa.eu/cas/serviceValidate
      query:
        userDetails: 'true'
        groups: '*'
      allowed_parameters:
        - service
        - ticket
        - pgtUrl
        - renew
        - format
        - userDetails
        - groups
    logout:
      uri: https://ecas.ec.europa.eu/cas/logout
      allowed_parameters:
        - service
